services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: servicedemo-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Chilly2025!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servicedemo-api
    restart: always
    depends_on:
      sqlserver:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ServiceDemoDB;User Id=sa;Password=Chilly2025!;TrustServerCertificate=True;MultipleActiveResultSets=True
       
volumes:
  sql_data:git