apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
  labels:
    app: mi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mi-app
        image: ${IMAGE_URL}
        ports:
        - containerPort: 8080        
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: connection-string-secret
              key: ConnectionStrings__DefaultConnection
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "499m"
            memory: "1Gi"
            ephemeral-storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  type: LoadBalancer
  selector:
    app: mi-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080