name: Continuos Integration
on:
  pull_request:
    branches: 
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: mi-app
  REPOSITORY: mi-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Descargando Repositorio
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restaurar Dependencias
        run: dotnet restore ServiceDemo.slnx

      - name: limpiar Solución
        run: dotnet clean ServiceDemo.slnx --configuration Release

      - name: Compilar Solución
        run: dotnet build ServiceDemo.slnx --no-restore --configuration Release

      - name: Tests unitarios 
        run: dotnet test ServiceDemo.slnx --no-build --configuration Release --verbosity normal

      - name: Restore local tools (Stryker)
        run: dotnet tool restore

      - name: Ejecutar Mutation Testing (Stryker)
        working-directory: tests/ServiceDemo.Tests
        run: dotnet stryker

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |
          IMAGE_URL="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL
